### ISSUE TITLE
Incremental Output from Source

### ISSUE THREAD

**Issue by tjdevries** [Shougo/denite.nvim#13]
Is it possible to give incremental output from a source? Say I have a really large grep that I'm doing, and I'd like the results to appear as they are found, not once they are all found?

Is this what you mean by `asynchronous sources support` in the TODOs?

**Comment by Shougo** [comment]
Yes.  It is already on the todo list.

**Comment by carlitux** [comment]
@Shougo maybe convert to generator the gather_candidates methods then add lines to denite buffer with some kind of events or callbacks.

Maybe something more complex is to use async and generators but we need python 3.5

**Comment by Shougo** [comment]
I have implemented the asynchronous.
But Popen.communicate() does not return the incremental output.

**Comment by tjdevries** [comment]
@shougo I will take a look at it today and try and submit a PR. I have some time today.

**Comment by Shougo** [comment]
I will use Vim8/neovim job API for it.

**Comment by HerringtonDarkholme** [comment]
There seems no easy way to implement this in Python3, if we don't want to drop support for 3.3-. Pyhton's standard library is poor, `asycio` is not available until 3.4. For compatibility we can use `process.stdout.readline` but it will still hang if process underlying has no output at all. But even if we do use `asyncio` it will require a huge rewriting.
